pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        mavenCentral()
        maven { url "https://api.xposed.info/" }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://dl.google.com/dl/android/maven2/' }
        mavenCentral()
        maven { url "https://api.xposed.info/" }
        maven { url "https://www.jitpack.io" }
        maven { url "https://s01.oss.sonatype.org/content/repositories/releases" }
    }
}
rootProject.name = "NoticeFix"
include ':app'
